use AgendaDB;

CREATE TABLE ESTABELECIMENTOS (
	ID_ESTABELECIMENTO INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	DESCRICAO VARCHAR(20) NOT NULL,
	ENDERECO VARCHAR(100) NOT NULL,
	USUARIO_ATUALIZACAO VARCHAR(20),
	DATA_ATUALIZACAO DATETIME
);

CREATE TABLE PROFISSIONAIS (
	ID_PROFISSIONAL INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(60) NOT NULL,
	ID_ESTABELECIMENTO INT NOT NULL,
	IS_ADMIN BIT NOT NULL,
	USUARIO_ATUALIZACAO VARCHAR(20),
	DATA_ATUALIZACAO DATETIME
);

CREATE TABLE CATEGORIA_SERVICOS (
	ID_CATEGORIA_SERVICO INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(30) NOT NULL
);

CREATE TABLE TIPO_SERVICOS (
	ID_TIPO_SERVICO INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(30) NOT NULL,
	ID_CATEGORIA_SERVICO INT,
	CONSTRAINT FK_TIPO_SERVICOS_CATEGORIA_SERVICO
		FOREIGN KEY(ID_CATEGORIA_SERVICO)
		REFERENCES CATEGORIA_SERVICOS(ID_CATEGORIA_SERVICO)
		ON DELETE NO ACTION
);

CREATE TABLE SERVICOS (
	ID_SERVICO INT IDENTITY(1,1) PRIMARY KEY,
	DESCRICAO VARCHAR(60) NOT NULL,
	VALOR INT NOT NULL,
	DURACAO TIME NOT NULL,
	ID_PROFISSIONAL INT NOT NULL,
	ID_TIPO_SERVICO INT NOT NULL,
	USUARIO_ATUALIZACAO VARCHAR(20),
	DATA_ATUALIZACAO DATETIME,
	CONSTRAINT FK_PROFISSIONAIS_SERVICOS
		FOREIGN KEY(ID_PROFISSIONAL)
		REFERENCES PROFISSIONAIS(ID_PROFISSIONAL)
		ON DELETE NO ACTION,
	CONSTRAINT FK_SERVICOS_TIPO_SERVICOS
        FOREIGN KEY (ID_TIPO_SERVICO)
        REFERENCES TIPO_SERVICOS(ID_TIPO_SERVICO)
        ON DELETE NO ACTION
);

CREATE TABLE TIPO_SITUACAO (
	ID_SITUACAO INT IDENTITY(1,1) PRIMARY KEY,
	SITUACAO VARCHAR(30) NOT NULL
);

CREATE TABLE CLIENTES (
	ID_CLIENTE INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(60) NOT NULL,
	TELEFONE VARCHAR(20) NOT NULL,
	CPF VARCHAR(11) UNIQUE NOT NULL,
	USUARIO VARCHAR(30) UNIQUE NOT NULL,
	SENHA VARCHAR(255) NOT NULL,
	USUARIO_ATUALIZACAO VARCHAR(20),
	DATA_ATUALIZACAO DATETIME,
);

CREATE TABLE AGENDA (
	ID_AGENDA INT IDENTITY(1,1) PRIMARY KEY,
	ID_PROFISSIONAL INT NOT NULL,
	DIAS_SEMANA INT NOT NULL,
	HORA_INICIO TIME NOT NULL,
	HORA_FIM TIME NOT NULL,
	USUARIO_ATUALIZACAO VARCHAR(20),
	DATA_ATUALIZACAO DATETIME,
	CONSTRAINT FK_PROFISSIONAIS_AGENDA
		FOREIGN KEY(ID_PROFISSIONAL)
		REFERENCES PROFISSIONAIS(ID_PROFISSIONAL)
		ON DELETE NO ACTION
);

CREATE TABLE AGENDAMENTOS (
	ID_AGENDAMENTO INT IDENTITY(1,1) PRIMARY KEY,
	ID_PROFISSIONAL INT NOT NULL,
	ID_SERVICO INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	NOME_CLIENTE VARCHAR(60) NOT NULL,
	TELEFONE_CLIENTE VARCHAR(20) UNIQUE NOT NULL,
	DATA DATE NOT NULL,
	HORA_INICIO TIME NOT NULL,
	HORA_FIM TIME NOT NULL,
	ID_SITUACAO INT NOT NULL,
	USUARIO_ATUALIZACAO VARCHAR(20),
	DATA_ATUALIZACAO DATETIME,
	CONSTRAINT FK_PROFISSIONAIS_AGENDAMENTOS
		FOREIGN KEY(ID_PROFISSIONAL)
		REFERENCES PROFISSIONAIS(ID_PROFISSIONAL)
		ON DELETE NO ACTION,
	CONSTRAINT FK_AGENDAMENTOS_SERVICOS
		FOREIGN KEY(ID_SERVICO)
		REFERENCES SERVICOS(ID_SERVICO)
		ON DELETE NO ACTION,
	CONSTRAINT FK_AGENDAMENTOS_CLIENTES
		FOREIGN KEY(ID_CLIENTE)
		REFERENCES CLIENTES(ID_CLIENTE)
		ON DELETE NO ACTION,
	CONSTRAINT FK_AGENDAMENTOS_TIPO_SITUACAO
		FOREIGN KEY(ID_SITUACAO)
		REFERENCES TIPO_SITUACAO(ID_SITUACAO)
		ON DELETE NO ACTION
);